[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -e ."]

[start]
cmd = "alembic upgrade head && uvicorn fantasai.main:app --host 0.0.0.0 --port $PORT"
