"""Trade builder: generate fair trade proposals given a target player.

Performs combinatorial search over the user's roster to find 3-5 packages
that are within the value band of the target player(s), using the same
talent-density adjustment as the trade evaluator. Context clues (e.g. "He
wants arms") steer the search toward pitcher-heavy or youth-heavy packages.
The other team's roster informs roster-need scoring so proposals feel
realistic — plus one wildcard that ignores roster fit entirely.

Purely functional — no DB dependency. LLM fit notes are generated by the
API layer after suggestions are selected.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from itertools import combinations
from typing import Optional

from fantasai.brain.trade_evaluator import (
    _adjusted_side_value,
    _pick_value,
)
from fantasai.engine.scoring import PlayerRanking

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MAX_PLAYERS_PER_SIDE = 3
ACCEPTANCE_BAND = 2.5       # ± score units around target give value
TOLERANCE_SCALE = 5.0       # slider ±1.0 maps to ±5.0 score units

# Draft pick round → pick string year (next draft after current season)
_PICK_YEAR = 2027

# Pick pairs to try: (my_rounds, their_rounds). Rounds 1-13 only; 14-21 are
# keeper slots and must never appear in trade offers.
# Ordered from "I give most extra" → "they give most extra".
_PICK_PAIRS: list[tuple[list[int], list[int]]] = [
    ([], []),            # no picks
    ([1], [3]),          # I sweeten with 1st, get their 3rd
    ([2], [3]),          # I sweeten with 2nd, get their 3rd
    ([1], [2]),          # I give 1st, get 2nd
    ([1], [1]),          # even 1st-for-1st
    ([2], [2]),          # even 2nd-for-2nd
    ([3], [2]),          # they give slightly more (2nd), I give 3rd
    ([3], [1]),          # they sweeten with 1st, I give 3rd
    ([2], [1]),          # they give 1st, I give 2nd
    ([1, 3], [1, 2]),    # 2-pick deal: they give slightly more
    ([1, 2], [1, 3]),    # 2-pick deal: I give slightly more
]


def _pick_round_str(round_num: int) -> str:
    suffixes = {1: "st", 2: "nd", 3: "rd"}
    suffix = suffixes.get(round_num if round_num < 21 else 0, "th")
    return f"{_PICK_YEAR} {round_num}{suffix} round"


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class TradeBuildContext:
    """All inputs needed to build trade suggestions."""

    my_rankings: list[PlayerRanking]        # my full roster with scores
    their_rankings: list[PlayerRanking]     # other team's roster (for need fit)
    target_rankings: list[PlayerRanking]    # players I want to receive
    context: Optional[str]                  # "He wants arms, needs OF help"
    value_tolerance: float                  # -1.0 (I want more back) → +1.0 (I'll overpay)
    scoring_categories: list[str]
    league_type: str = "h2h_categories"
    # player_id → positions for all my roster players (for positional warnings)
    my_roster_positions: dict[int, list[str]] = field(default_factory=dict)


@dataclass
class _Candidate:
    """Internal candidate before label assignment."""

    give_rankings: list[PlayerRanking]
    give_picks: list[str]
    receive_picks: list[str]
    give_value: float
    receive_value: float
    value_diff: float           # receive - give (positive = I get more)
    target_diff: float          # slider-calibrated target differential
    fairness_score: float       # 0–1, how close to target_diff
    context_fit_score: float    # 0–1
    roster_need_score: float    # 0–1, how much other team needs these players


@dataclass
class TradeSuggestion:
    """One fully-formed trade suggestion (API layer adds fit_note via LLM)."""

    label: str
    give_player_ids: list[int]
    give_picks: list[str]
    receive_player_ids: list[int]
    receive_picks: list[str]
    give_value: float
    receive_value: float
    value_differential: float
    fairness_score: float
    positional_warnings: list[str]
    respects_roster_needs: bool
    fit_note: str = ""


# ---------------------------------------------------------------------------
# Context signal parsing
# ---------------------------------------------------------------------------

def _parse_context_signals(context: Optional[str]) -> set[str]:
    """Extract intent signals from manager context string.

    Returns a set of signal strings like "SP", "RP", "OF", "young", "multi".
    """
    if not context:
        return set()

    lower = context.lower()
    signals: set[str] = set()

    sp_kws = ("arm", "arms", "pitcher", "pitchers", "pitching", "sp", "starter",
              "starters", "ace", "rotation")
    rp_kws = ("rp", "reliever", "relievers", "closer", "closers", "bullpen",
              "save", "saves")
    young_kws = ("young", "youth", "prospect", "prospects", "future")
    multi_kws = ("multiple", "several", "fill spots", "few positions")

    if any(kw in lower for kw in sp_kws):
        signals.add("SP")
    if any(kw in lower for kw in rp_kws):
        signals.add("RP")
    if any(kw in lower for kw in young_kws):
        signals.add("young")
    if any(kw in lower for kw in multi_kws):
        signals.add("multi")

    pos_map = {
        "outfield": "OF", " of ": "OF", "outfielder": "OF",
        "shortstop": "SS", " ss ": "SS",
        "first base": "1B", " 1b ": "1B",
        "second base": "2B", " 2b ": "2B",
        "third base": "3B", " 3b ": "3B",
        "catcher": "C", " c ": "C",
    }
    for kw, pos in pos_map.items():
        if kw in f" {lower} ":
            signals.add(pos)

    return signals


# ---------------------------------------------------------------------------
# Scoring helpers
# ---------------------------------------------------------------------------

def _context_fit_score(give_rankings: list[PlayerRanking], signals: set[str]) -> float:
    """0–1: how well the offer matches what the other manager signalled."""
    if not signals:
        return 0.5

    n = max(len(give_rankings), 1)
    score = 0.0

    for sig in signals:
        if sig == "SP":
            score += sum(1 for r in give_rankings if "SP" in r.positions) / n
        elif sig == "RP":
            score += sum(1 for r in give_rankings if "RP" in r.positions) / n
        elif sig in {"OF", "SS", "1B", "2B", "3B", "C"}:
            score += sum(1 for r in give_rankings if sig in r.positions) / n
        elif sig == "multi":
            score += min((len(give_rankings) - 1) * 0.5, 1.0)
        elif sig == "young":
            # We don't have age on PlayerRanking; give a flat neutral bonus
            # so "young" context doesn't zero out the score.
            score += 0.4

    return min(score / len(signals), 1.0)


def _roster_need_score(
    give_rankings: list[PlayerRanking],
    their_rankings: list[PlayerRanking],
) -> float:
    """0–1: how scarce these positions are on the other team's roster."""
    if not their_rankings:
        return 0.5

    their_pos_counts: dict[str, int] = {}
    for r in their_rankings:
        for pos in r.positions:
            their_pos_counts[pos] = their_pos_counts.get(pos, 0) + 1

    scores = []
    for r in give_rankings:
        primary = r.positions[0] if r.positions else None
        if primary is None:
            scores.append(0.5)
            continue
        cnt = their_pos_counts.get(primary, 0)
        if cnt == 0:
            scores.append(1.0)
        elif cnt == 1:
            scores.append(0.8)
        elif cnt == 2:
            scores.append(0.5)
        elif cnt == 3:
            scores.append(0.25)
        else:
            scores.append(0.1)

    return sum(scores) / len(scores) if scores else 0.5


def _composite_score(c: _Candidate, ignore_need: bool = False) -> float:
    need = c.roster_need_score if not ignore_need else 0.5
    return 0.45 * c.fairness_score + 0.35 * c.context_fit_score + 0.20 * need


# ---------------------------------------------------------------------------
# Positional warnings
# ---------------------------------------------------------------------------

def _positional_warnings(
    give_rankings: list[PlayerRanking],
    my_rankings: list[PlayerRanking],
) -> list[str]:
    """Warn when a trade leaves the user short at a position."""
    giving_ids = {r.player_id for r in give_rankings}
    remaining_by_pos: dict[str, int] = {}
    for r in my_rankings:
        if r.player_id in giving_ids:
            continue
        for pos in r.positions:
            remaining_by_pos[pos] = remaining_by_pos.get(pos, 0) + 1

    warnings: list[str] = []
    warned_players: set[int] = set()
    for r in give_rankings:
        if r.player_id in warned_players:
            continue
        for pos in r.positions:
            remaining = remaining_by_pos.get(pos, 0)
            if remaining == 0:
                warnings.append(
                    f"Trading {r.name} leaves you with no {pos} coverage — "
                    f"significant positional weakness."
                )
                warned_players.add(r.player_id)
                break
            elif remaining == 1:
                warnings.append(
                    f"Trading {r.name} leaves you with just 1 {pos} remaining."
                )
                warned_players.add(r.player_id)
                break

    return warnings


# ---------------------------------------------------------------------------
# Label assignment
# ---------------------------------------------------------------------------

def _assign_label(
    candidate: _Candidate,
    signals: set[str],
    existing_labels: list[str],
    is_wildcard: bool = False,
) -> str:
    """Assign a human-readable label based on structure and context signals."""
    if is_wildcard:
        return "Wildcard"

    n = len(candidate.give_rankings)
    has_picks = bool(candidate.give_picks)

    # Context-driven labels take priority
    if "SP" in signals and n > 0 and all("SP" in r.positions for r in candidate.give_rankings):
        lbl = "Pitcher Package"
        if lbl not in existing_labels:
            return lbl
    if "RP" in signals and n > 0 and all("RP" in r.positions for r in candidate.give_rankings):
        lbl = "Closer Package"
        if lbl not in existing_labels:
            return lbl

    # Structure-based labels
    if has_picks and n == 1:
        lbl = "Draft Pick Sweetener"
        return lbl if lbl not in existing_labels else "Pick-Heavy Deal"
    if has_picks and n > 1:
        lbl = "Pick-Heavy Package"
        return lbl if lbl not in existing_labels else f"{n}-Player Pick Deal"
    if n == 1:
        lbl = "1-for-1 Trade"
        return lbl if lbl not in existing_labels else "Straight Swap"
    if n == 2:
        lbl = "2-for-1 Trade"
        return lbl if lbl not in existing_labels else "Two-Player Package"
    if n == 3:
        lbl = "3-Player Package"
        return lbl if lbl not in existing_labels else "Full Package"

    return f"{n}-Player Offer"


# ---------------------------------------------------------------------------
# Main build function
# ---------------------------------------------------------------------------

def build_trades(ctx: TradeBuildContext) -> list[TradeSuggestion]:
    """Generate 3-5 diverse trade suggestions for the target player(s).

    Algorithm:
    1. Compute target receive value (density-adjusted).
    2. Derive target give value from slider (value_tolerance).
    3. Enumerate all combos of my players (1-3) × pick pairs.
    4. Filter to candidates within ACCEPTANCE_BAND of the target give value.
    5. Score each candidate (fairness + context fit + roster need fit).
    6. Select diverse set of 3-5 with distinct structures and labels.
    """
    if not ctx.target_rankings:
        return []

    target_scores = [r.score for r in ctx.target_rankings]
    target_recv_value = _adjusted_side_value(target_scores)

    # Slider semantics:
    #   value_tolerance = -1.0 → "less" → target_diff = +5 (I want more back)
    #   value_tolerance =  0.0 → fair   → target_diff =  0
    #   value_tolerance = +1.0 → "more" → target_diff = -5 (I'll give more)
    target_diff = -ctx.value_tolerance * TOLERANCE_SCALE
    target_give_value = target_recv_value - target_diff

    signals = _parse_context_signals(ctx.context)
    target_ids = {r.player_id for r in ctx.target_rankings}
    my_available = [r for r in ctx.my_rankings if r.player_id not in target_ids]

    if not my_available:
        return []

    all_candidates: list[_Candidate] = []
    n_max = min(MAX_PLAYERS_PER_SIDE, len(my_available))

    for n_players in range(1, n_max + 1):
        for player_combo in combinations(my_available, n_players):
            player_give_adj = _adjusted_side_value([r.score for r in player_combo])

            for my_rounds, their_rounds in _PICK_PAIRS:
                my_picks = [_pick_round_str(r) for r in my_rounds]
                their_picks = [_pick_round_str(r) for r in their_rounds]
                my_pick_val = sum(_pick_value(p) for p in my_picks)
                their_pick_val = sum(_pick_value(p) for p in their_picks)

                give_value = player_give_adj + my_pick_val
                receive_value = target_recv_value + their_pick_val
                value_diff = receive_value - give_value

                if abs(value_diff - target_diff) > ACCEPTANCE_BAND:
                    continue

                fairness = max(0.0, 1.0 - abs(value_diff - target_diff) / ACCEPTANCE_BAND)
                ctx_fit = _context_fit_score(list(player_combo), signals)
                need_fit = _roster_need_score(list(player_combo), ctx.their_rankings)

                all_candidates.append(_Candidate(
                    give_rankings=list(player_combo),
                    give_picks=my_picks,
                    receive_picks=their_picks,
                    give_value=round(give_value, 3),
                    receive_value=round(receive_value, 3),
                    value_diff=round(value_diff, 3),
                    target_diff=target_diff,
                    fairness_score=round(fairness, 3),
                    context_fit_score=round(ctx_fit, 3),
                    roster_need_score=round(need_fit, 3),
                ))

    if not all_candidates:
        logger.info(
            "build_trades: no candidates in band (target_give=%.2f, n_my=%d)",
            target_give_value,
            len(my_available),
        )
        return []

    logger.info("build_trades: %d candidates before selection", len(all_candidates))
    return _select_diverse(all_candidates, ctx, signals)


def _select_diverse(
    candidates: list[_Candidate],
    ctx: TradeBuildContext,
    signals: set[str],
) -> list[TradeSuggestion]:
    """Pick 3-5 structurally distinct suggestions from the candidate pool."""

    def to_suggestion(
        c: _Candidate, label: str, respects_needs: bool
    ) -> TradeSuggestion:
        warnings = _positional_warnings(c.give_rankings, ctx.my_rankings)
        return TradeSuggestion(
            label=label,
            give_player_ids=[r.player_id for r in c.give_rankings],
            give_picks=c.give_picks,
            receive_player_ids=[r.player_id for r in ctx.target_rankings],
            receive_picks=c.receive_picks,
            give_value=c.give_value,
            receive_value=c.receive_value,
            value_differential=c.value_diff,
            fairness_score=c.fairness_score,
            positional_warnings=warnings,
            respects_roster_needs=respects_needs,
        )

    selected: list[TradeSuggestion] = []
    used_keys: set[frozenset[int]] = set()
    existing_labels: list[str] = []

    def pkey(c: _Candidate) -> frozenset[int]:
        return frozenset(r.player_id for r in c.give_rankings)

    def pick_best(
        group: list[_Candidate], ignore_need: bool = False
    ) -> Optional[_Candidate]:
        avail = [c for c in group if pkey(c) not in used_keys]
        return max(avail, key=lambda c: _composite_score(c, ignore_need), default=None)

    no_pick = [c for c in candidates if not c.give_picks]
    with_picks = [c for c in candidates if c.give_picks]
    one_pl = [c for c in no_pick if len(c.give_rankings) == 1]
    two_pl = [c for c in no_pick if len(c.give_rankings) == 2]
    three_pl = [c for c in no_pick if len(c.give_rankings) == 3]

    # Slot 1: Best overall (need-aware)
    best = pick_best(candidates)
    if best:
        label = _assign_label(best, signals, existing_labels)
        existing_labels.append(label)
        selected.append(to_suggestion(best, label, respects_needs=True))
        used_keys.add(pkey(best))

    # Slot 2: Different player count from slot 1
    slot1_n = len(selected[0].give_player_ids) if selected else 0
    structure_groups = [
        g for g in [one_pl, two_pl, three_pl]
        if g and (not selected or len(g[0].give_rankings) != slot1_n)
    ]
    for group in structure_groups:
        if len(selected) >= 2:
            break
        c = pick_best(group)
        if c:
            label = _assign_label(c, signals, existing_labels)
            existing_labels.append(label)
            selected.append(to_suggestion(c, label, respects_needs=True))
            used_keys.add(pkey(c))

    # Slot 3: Context-fit champion (if signals exist and we have room)
    if signals and len(selected) < 4:
        ctx_champs = sorted(
            [c for c in no_pick if c.context_fit_score >= 0.5],
            key=lambda c: -_composite_score(c),
        )
        c = pick_best(ctx_champs)
        if c:
            label = _assign_label(c, signals, existing_labels)
            if label not in existing_labels:
                existing_labels.append(label)
                selected.append(to_suggestion(c, label, respects_needs=True))
                used_keys.add(pkey(c))

    # Slot 4: Pick sweetener (if any exist)
    if with_picks and len(selected) < 5:
        c = pick_best(with_picks)
        if c:
            label = _assign_label(c, signals, existing_labels)
            existing_labels.append(label)
            selected.append(to_suggestion(c, label, respects_needs=True))
            used_keys.add(pkey(c))

    # Slot 5 (or fill): Wildcard — ignores roster need
    remaining = [c for c in candidates if pkey(c) not in used_keys]
    wildcard = max(
        remaining,
        key=lambda c: _composite_score(c, ignore_need=True),
        default=None,
    )
    if wildcard and len(selected) < 5:
        selected.append(to_suggestion(wildcard, "Wildcard", respects_needs=False))
        used_keys.add(pkey(wildcard))

    # Guarantee at least 3 by filling with best unused regardless of structure
    all_sorted = sorted(
        [c for c in candidates if pkey(c) not in used_keys],
        key=lambda c: -_composite_score(c),
    )
    for c in all_sorted:
        if len(selected) >= 3:
            break
        label = _assign_label(c, signals, existing_labels)
        existing_labels.append(label)
        selected.append(to_suggestion(c, label, respects_needs=True))
        used_keys.add(pkey(c))

    return selected[:5]
