"""add data_source to player_stats

Revision ID: 234fc4c032f8
Revises: 5ab30e933271
Create Date: 2026-03-27 08:38:33.139417
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234fc4c032f8'
down_revision: Union[str, None] = '5ab30e933271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('player_stats', sa.Column('data_source', sa.String(length=20), nullable=False, server_default='projection'))
    # Backfill nulls before adding NOT NULL constraint
    op.execute("UPDATE teams SET il_player_ids = '[]'::json WHERE il_player_ids IS NULL")
    op.execute("UPDATE teams SET injured_player_statuses = '{}'::json WHERE injured_player_statuses IS NULL")
    op.alter_column('teams', 'il_player_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('teams', 'injured_player_statuses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'injured_player_statuses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('teams', 'il_player_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('player_stats', 'data_source')
    # ### end Alembic commands ###
