"""add ranking snapshots table

Revision ID: 5ab30e933271
Revises: 1dfbb6e08060
Create Date: 2026-03-26 17:19:15.664337
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ab30e933271'
down_revision: Union[str, None] = '1dfbb6e08060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('ranking_type', sa.String(length=20), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('stat_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'ranking_type', 'horizon', 'snapshot_date', name='uq_ranking_snapshot')
    )
    op.create_index(op.f('ix_ranking_snapshots_player_id'), 'ranking_snapshots', ['player_id'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_snapshot_date'), 'ranking_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_snapshots_snapshot_date'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_player_id'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    # ### end Alembic commands ###
