"""add transactions table

Revision ID: 5ebf874800fb
Revises: 234fc4c032f8
Create Date: 2026-03-27 13:02:05.539721
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebf874800fb'
down_revision: Union[str, None] = '234fc4c032f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yahoo_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('league_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('grade_letter', sa.String(length=3), nullable=True),
    sa.Column('grade_score', sa.Float(), nullable=True),
    sa.Column('grade_rationale', sa.Text(), nullable=True),
    sa.Column('card_image_path', sa.String(length=500), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('yahoo_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_graded_at', 'transactions', ['graded_at'], unique=False)
    op.create_index('ix_transactions_league_id', 'transactions', ['league_id'], unique=False)
    op.create_index(op.f('ix_transactions_share_token'), 'transactions', ['share_token'], unique=True)
    op.create_index(op.f('ix_transactions_yahoo_transaction_id'), 'transactions', ['yahoo_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_yahoo_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_share_token'), table_name='transactions')
    op.drop_index('ix_transactions_league_id', table_name='transactions')
    op.drop_index('ix_transactions_graded_at', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
