"""add data_source to player_stats unique constraint and is_backfill to transactions

Revision ID: 721421699845
Revises: 5ebf874800fb
Create Date: 2026-03-27 13:39:34.362506
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721421699845'
down_revision: Union[str, None] = '5ebf874800fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_player_stats'), 'player_stats', type_='unique')
    op.create_unique_constraint('uq_player_stats', 'player_stats', ['player_id', 'season', 'week', 'stat_type', 'data_source'])
    op.add_column('transactions', sa.Column('is_backfill', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_backfill')
    op.drop_constraint('uq_player_stats', 'player_stats', type_='unique')
    op.create_unique_constraint(op.f('uq_player_stats'), 'player_stats', ['player_id', 'season', 'week', 'stat_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
