"""add blurb_batches table

Revision ID: 83900d6ce121
Revises: k2l3m4n5o6p7
Create Date: 2026-04-02 20:39:32.135170
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83900d6ce121'
down_revision: Union[str, None] = 'k2l3m4n5o6p7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blurb_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('batch_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.drop_index(op.f('ix_rankings_share_token'), table_name='rankings')
    op.create_unique_constraint(None, 'rankings', ['share_token'])
    op.alter_column('teams', 'bench_player_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'bench_player_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'rankings', type_='unique')
    op.create_index(op.f('ix_rankings_share_token'), 'rankings', ['share_token'], unique=True)
    op.drop_table('blurb_batches')
    # ### end Alembic commands ###
