"""add_player_rolling_stats

Revision ID: a0b45d6b9db7
Revises: 
Create Date: 2026-03-14 18:05:52.845475
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b45d6b9db7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_id', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('sport', sa.String(length=10), nullable=False),
    sa.Column('scoring_categories', sa.JSON(), nullable=False),
    sa.Column('league_type', sa.String(length=30), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('roster_positions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mlbam_id', sa.Integer(), nullable=True),
    sa.Column('fangraphs_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_rolling_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('counting_stats', sa.JSON(), nullable=False),
    sa.Column('rate_stats', sa.JSON(), nullable=False),
    sa.Column('window_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'window_days', 'stat_type', name='uq_player_rolling_stats')
    )
    op.create_index(op.f('ix_player_rolling_stats_player_id'), 'player_rolling_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_rolling_stats_season'), 'player_rolling_stats', ['season'], unique=False)
    op.create_index(op.f('ix_player_rolling_stats_window_days'), 'player_rolling_stats', ['window_days'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('counting_stats', sa.JSON(), nullable=False),
    sa.Column('rate_stats', sa.JSON(), nullable=False),
    sa.Column('advanced_stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'week', 'stat_type', name='uq_player_stats')
    )
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('ranking_type', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=False),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category_contributions', sa.JSON(), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('league_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'ranking_type', 'period', 'league_id', name='uq_ranking')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=100), nullable=False),
    sa.Column('manager_name', sa.String(length=200), nullable=False),
    sa.Column('roster', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rec_type', sa.String(length=30), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('rationale_blurb', sa.Text(), nullable=True),
    sa.Column('category_impact', sa.JSON(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('teams')
    op.drop_table('rankings')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_player_rolling_stats_window_days'), table_name='player_rolling_stats')
    op.drop_index(op.f('ix_player_rolling_stats_season'), table_name='player_rolling_stats')
    op.drop_index(op.f('ix_player_rolling_stats_player_id'), table_name='player_rolling_stats')
    op.drop_table('player_rolling_stats')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
