"""add_injury_records_and_player_risk_flags

Revision ID: d7eddb613f65
Revises: b1c2d3e4f5a6
Create Date: 2026-03-17 22:27:28.843326
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eddb613f65'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('injury_description', sa.String(length=500), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_records_player_id'), 'injury_records', ['player_id'], unique=True)
    op.add_column('players', sa.Column('risk_flag', sa.String(length=30), nullable=True))
    op.add_column('players', sa.Column('risk_note', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'risk_note')
    op.drop_column('players', 'risk_flag')
    op.drop_index(op.f('ix_injury_records_player_id'), table_name='injury_records')
    op.drop_table('injury_records')
    # ### end Alembic commands ###
