"""add scoring grid snapshot table

Revision ID: e3f1a411dbd1
Revises: l3m4n5o6p7q8
Create Date: 2026-04-21 17:34:53.516379
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f1a411dbd1'
down_revision: Union[str, None] = 'l3m4n5o6p7q8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_grid_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=100), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_stats', sa.JSON(), nullable=False),
    sa.Column('teams_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'week', name='uq_scoring_grid_league_season_week')
    )
    op.create_index(op.f('ix_scoring_grid_snapshots_league_id'), 'scoring_grid_snapshots', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_grid_snapshots_league_id'), table_name='scoring_grid_snapshots')
    op.drop_table('scoring_grid_snapshots')
    # ### end Alembic commands ###
