"""add yahoo_team_key to teams

Revision ID: f69ae681ef16
Revises: acbc21dafa6f
Create Date: 2026-03-25 20:37:47.427676
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f69ae681ef16'
down_revision: Union[str, None] = 'acbc21dafa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anon_usage_ip_hash'), table_name='anonymous_usage')
    op.create_index(op.f('ix_anonymous_usage_ip_hash'), 'anonymous_usage', ['ip_hash'], unique=False)
    op.drop_index(op.f('ix_prospect_profiles_pav_score'), table_name='prospect_profiles')
    op.add_column('teams', sa.Column('yahoo_team_key', sa.String(length=100), nullable=True))
    op.alter_column('teams', 'roster_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.create_index(op.f('ix_teams_yahoo_team_key'), 'teams', ['yahoo_team_key'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_teams_yahoo_team_key'), table_name='teams')
    op.alter_column('teams', 'roster_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('teams', 'yahoo_team_key')
    op.create_index(op.f('ix_prospect_profiles_pav_score'), 'prospect_profiles', ['pav_score'], unique=False)
    op.drop_index(op.f('ix_anonymous_usage_ip_hash'), table_name='anonymous_usage')
    op.create_index(op.f('ix_anon_usage_ip_hash'), 'anonymous_usage', ['ip_hash'], unique=False)
    # ### end Alembic commands ###
